<a href="https://colab.research.google.com/github/drskprabhakar/Axial-Length-Prediction-ML-Regression-mode/blob/main/DR_CNN_16_layers_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import os
import numpy as np
os.listdir('/content/drive/MyDrive/DR fundus images/split')

['train', 'val', 'test']

In [3]:
os.listdir('/content/drive/MyDrive/DR fundus images/split/train')

['DR2', 'DR3', 'DR1']

In [41]:
from keras.preprocessing.image import ImageDataGenerator
datagen = ImageDataGenerator()

trainimages = datagen.flow_from_directory('/content/drive/MyDrive/DR fundus images/split/train',
                                          target_size=(224,224))

valimages = datagen.flow_from_directory('/content/drive/MyDrive/DR fundus images/split/val',
                                          target_size=(224,224))

testimages = datagen.flow_from_directory('/content/drive/MyDrive/DR fundus images/split/test',
                                          target_size=(224,224))


Found 78 images belonging to 3 classes.
Found 14 images belonging to 3 classes.
Found 14 images belonging to 3 classes.


In [68]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense


model = Sequential()

# Block 1
model.add(Conv2D(16, (3, 3), activation='relu', padding='same', input_shape=(224,224, 3)))

model.add(MaxPooling2D((2, 2), strides=(2, 2)))

# Block 2
model.add(Conv2D(16, (3, 3), activation='relu', padding='same'))

model.add(MaxPooling2D((2, 2), strides=(2, 2)))

# Block 3
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))

model.add(MaxPooling2D((2, 2), strides=(2, 2)))

# Block 4
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))

model.add(MaxPooling2D((2, 2), strides=(2, 2)))

# Block 5
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))

model.add(MaxPooling2D((2, 2), strides=(2, 2)))

# Flatten
model.add(Flatten())

# Fully connected layers

model.add(Dense(128, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_49 (Conv2D)          (None, 224, 224, 16)      448       
                                                                 
 max_pooling2d_25 (MaxPooli  (None, 112, 112, 16)      0         
 ng2D)                                                           
                                                                 
 conv2d_50 (Conv2D)          (None, 112, 112, 16)      2320      
                                                                 
 max_pooling2d_26 (MaxPooli  (None, 56, 56, 16)        0         
 ng2D)                                                           
                                                                 
 conv2d_51 (Conv2D)          (None, 56, 56, 64)        9280      
                                                                 
 max_pooling2d_27 (MaxPooli  (None, 28, 28, 64)       

In [69]:
model.fit(trainimages,
          batch_size=32,
          epochs=10,
          validation_data=valimages)
model.save('DRCNN16layers_model.keras')

Epoch 1/10
3/3 [==============================] - 12s 3s/step - loss: 26.9370 - accuracy: 0.3462 - val_loss: 3.7464 - val_accuracy: 0.5000
Epoch 2/10
3/3 [==============================] - 8s 2s/step - loss: 3.6995 - accuracy: 0.4487 - val_loss: 1.3921 - val_accuracy: 0.5000
Epoch 3/10
3/3 [==============================] - 9s 4s/step - loss: 1.4684 - accuracy: 0.4744 - val_loss: 1.2847 - val_accuracy: 0.5000
Epoch 4/10
3/3 [==============================] - 8s 3s/step - loss: 0.9250 - accuracy: 0.5385 - val_loss: 1.0181 - val_accuracy: 0.5000
Epoch 5/10
3/3 [==============================] - 9s 3s/step - loss: 0.8969 - accuracy: 0.5513 - val_loss: 0.7916 - val_accuracy: 0.6429
Epoch 6/10
3/3 [==============================] - 9s 4s/step - loss: 0.7404 - accuracy: 0.6538 - val_loss: 0.7876 - val_accuracy: 0.5714
Epoch 7/10
3/3 [==============================] - 8s 3s/step - loss: 0.6868 - accuracy: 0.6923 - val_loss: 0.6804 - val_accuracy: 0.7143
Epoch 8/10
3/3 [=======================

In [70]:
y_pred = model.predict(testimages)
y_pred

1/1 [==============================] - 1s 1s/step


array([[7.5772399e-01, 5.5236313e-02, 1.8703970e-01],
       [7.2642851e-01, 4.0456153e-02, 2.3311530e-01],
       [2.2634497e-02, 3.2429752e-01, 6.5306789e-01],
       [8.8139996e-03, 9.4268012e-01, 4.8505835e-02],
       [7.6633454e-03, 9.7769834e-02, 8.9456689e-01],
       [2.9744754e-02, 2.6828232e-01, 7.0197290e-01],
       [8.0566789e-04, 9.7429085e-01, 2.4903499e-02],
       [1.5201463e-02, 2.6057389e-01, 7.2422463e-01],
       [5.8089342e-02, 3.2738864e-01, 6.1452192e-01],
       [2.0575097e-02, 1.3878417e-01, 8.4064078e-01],
       [1.1866937e-01, 5.1049125e-01, 3.7083933e-01],
       [3.4524032e-01, 8.9488380e-02, 5.6527120e-01],
       [1.1066073e-02, 1.1319434e-01, 8.7573957e-01],
       [3.6262579e-02, 3.9701375e-01, 5.6672364e-01]], dtype=float32)

In [71]:
y_pred1 = np.argmax(y_pred, axis=1)
y_pred1

array([0, 0, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2])

In [14]:
y_true = testimages.classes
y_true

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2], dtype=int32)

In [72]:
from sklearn import metrics
metrics.confusion_matrix(y_true, y_pred1)

array([[2, 0, 1],
       [0, 2, 4],
       [0, 1, 4]])

In [73]:
print(metrics.classification_report(y_true, y_pred1,
                                    target_names=['DR1','DR2','DR3']))

              precision    recall  f1-score   support

         DR1       1.00      0.67      0.80         3
         DR2       0.67      0.33      0.44         6
         DR3       0.44      0.80      0.57         5

    accuracy                           0.57        14
   macro avg       0.70      0.60      0.61        14
weighted avg       0.66      0.57      0.57        14

