<a href="https://colab.research.google.com/github/drskprabhakar/Axial-Length-Prediction-ML-Regression-mode/blob/main/Glaucoma_log_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel('/content/drive/MyDrive/glaucoma dataset.xlsx')

In [4]:
df.shape

(27, 2)

In [5]:
df.columns

Index(['age', 'glaucoma'], dtype='object')

In [ ]:
df.head()

In [9]:
x = df.drop(['glaucoma'], axis=1).values
y = df['glaucoma'].values

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [11]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

In [14]:
y_predlinear = model.predict(x_test)
model.score(x_test, y_test)

0.8333333333333334

In [15]:
model.predict_proba(x_test)

array([[0.97584218, 0.02415782],
       [0.93039196, 0.06960804],
       [0.96175353, 0.03824647],
       [0.91943763, 0.08056237],
       [0.23162449, 0.76837551],
       [0.97584218, 0.02415782]])

In [16]:
x_test

array([[18],
       [25],
       [21],
       [26],
       [49],
       [18]])

In [17]:
from sklearn.metrics import confusion_matrix, classification_report
confusion_matrix(y_test, y_predlinear)

array([[4, 0],
       [1, 1]])

In [18]:
print(classification_report(y_test, y_predlinear))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89         4
           1       1.00      0.50      0.67         2

    accuracy                           0.83         6
   macro avg       0.90      0.75      0.78         6
weighted avg       0.87      0.83      0.81         6



In [19]:
model.predict([[34]])

array([0])

In [26]:
model.predict([[45]])

array([1])