<a href="https://colab.research.google.com/github/drskprabhakar/Axial-Length-Prediction-ML-Regression-mode/blob/main/Kidney_stone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
import pandas as pd
import numpy as np

In [61]:
df = pd.read_excel('/content/drive/MyDrive/kindey stone urine analysis copy.xlsx')

In [62]:
df.shape

(79, 7)

In [63]:
df.columns

Index(['gravity', 'ph', 'osmo', 'cond', 'urea', 'calc', 'target'], dtype='object')

In [120]:
df.head()

gravity    ph  osmo  cond  urea  calc  target
0    1.021  4.91   725  14.0   443  2.45       0
1    1.017  5.74   577  20.0   296  4.49       0
2    1.008  7.20   321  14.9   101  2.36       0
3    1.011  5.51   408  12.6   224  2.15       0
4    1.005  6.52   187   7.5    91  1.16       0

In [121]:
df.isnull().sum()

gravity    0
ph         0
osmo       0
cond       0
urea       0
calc       0
target     0
dtype: int64

In [122]:
x = df.drop(['target'], axis=1).values
y = df['target'].values

In [123]:
from sklearn.model_selection import train_test_split
x_train,y_train,x_test,y_test = train_test_split(x,y,test_size=0.3)

In [91]:
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression()
model1.fit(x, y)

LogisticRegression()

In [95]:
y_pred1 = model1.predict(x)
model1.score(x,y)

0.7974683544303798

In [98]:
from sklearn.metrics import confusion_matrix, classification_report
confusion_matrix(y, y_pred1)

array([[39,  6],
       [10, 24]])

In [99]:
print(classification_report(y, y_pred1))

              precision    recall  f1-score   support

           0       0.80      0.87      0.83        45
           1       0.80      0.71      0.75        34

    accuracy                           0.80        79
   macro avg       0.80      0.79      0.79        79
weighted avg       0.80      0.80      0.80        79



In [100]:
from sklearn.ensemble import RandomForestClassifier
modelr = RandomForestClassifier()
modelr.fit(x,y)

RandomForestClassifier()

In [102]:
y_predr = modelr.predict(x)
modelr.score(x,y)

1.0

In [103]:
confusion_matrix(y,y_predr)

array([[45,  0],
       [ 0, 34]])

In [104]:
print(classification_report(y, y_predr))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        45
           1       1.00      1.00      1.00        34

    accuracy                           1.00        79
   macro avg       1.00      1.00      1.00        79
weighted avg       1.00      1.00      1.00        79



In [105]:
from sklearn.tree import DecisionTreeClassifier
modelt=DecisionTreeClassifier()
modelt.fit(x,y)

DecisionTreeClassifier()

In [107]:
y_predt = modelt.predict(x)
modelt.score(x,y)

1.0

In [109]:
from sklearn.svm import SVC
models=SVC()
models.fit(x,y)

SVC()

In [113]:
y_preds= models.predict(x)
models.score(x, y_preds)

1.0

In [116]:
df.head()

gravity    ph  osmo  cond  urea  calc  target
0    1.021  4.91   725  14.0   443  2.45       0
1    1.017  5.74   577  20.0   296  4.49       0
2    1.008  7.20   321  14.9   101  2.36       0
3    1.011  5.51   408  12.6   224  2.15       0
4    1.005  6.52   187   7.5    91  1.16       0

In [117]:
modelr.predict([[1.021,	4.91,	725,	14.0,	443,	2.45]])

array([0])

In [118]:
df.tail()

gravity    ph  osmo  cond  urea   calc  target
74    1.025  7.90   721  23.6   301   9.04       1
75    1.017  4.81   410  13.3   195   0.58       1
76    1.024  5.40   803  21.8   394   7.82       1
77    1.016  6.81   594  21.4   255  12.20       1
78    1.015  6.03   416  12.8   178   9.39       1

In [119]:
modelr.predict([[1.025,	7.90,	721,	23.6,	301,	9.04]])

array([1])